backend/controllers/CartController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Cart;
use app\models\ImageUpload;
use app\models\Helper;
use yii\data\Pagination;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FurnituresController implements the CRUD actions for Furnitures model.
 */
class CartController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Furnitures models.
     * @return mixed
     */
    public function actionIndex($page = 1)
    {
      $criteria = Cart::criteria();
      $criteria = Helper::setFilter($criteria);
      $pagination = new Pagination(['totalCount' => $criteria->count(), 'pageSize' => 20]);
      $data = $criteria->offset($pagination->offset)
                    ->limit($pagination->limit)
                    ->orderBy("done ASC")
                    ->all();

      $pages = Helper::pages($pagination->totalCount, $pagination->pageSize, $page);

      return $this->render('index', [
        'table_data' => $data,
        'pages' => $pages,
      ]);
    }

    /**
    * Добавление новой записи
    */
    public function actionAdd()
    {
      $model = new Slider;

      // Если получили данные для добавления
      if (isset($_POST['data'])) {
        $model->attributes = $_POST['data'];

        // Проверяем правильно ли введены данные
        if (!$model->validate()) {
          $message = $model->getErrors();
          $message = array_shift($message);
          return '{"status":"danger","text":"' . $message[0] . '", "code":"'.$answer['code'].'"}';
        }

        // заливаем фото в нужную папку
        if(strlen($model->image)){
          $answer = $model->uploadImage($model->image);
          if (!$answer['status']) {
            return '{"status":"danger", "text":"'.$answer['text'].'", "code":"'.$answer['code'].'"}';
          }
        }

        // Сохраним наши данные
        if (!$model->save()) {
          $message = $model->getErrors();
          $message = array_shift($message);
          return '{"status":"danger","text":"' . $message[0] . '"}';
        }

        // Подготовим вывод данных
        $data['status'] = "success";
        $data['html'] = $this->renderFile('@app/views/cart/_view.php', [
        'table_data' => [$model],
        ]);

        return json_encode($data);
      }

      return $this->renderFile('@app/views/cart/_form.php', [
      'form' => $model,
      ]);
    }

    /**
    *  Редактирование записи
    */
    public function actionUpdate($id)
    {
      $model = $this->findModel($id);

      // Если получили данные для добавления
      if (isset($_POST['data'])) {
        $model->attributes = $_POST['data'];

        if ($model->oldAttributes['done'] != $model->attributes['done']) {
          if ($model->done) {
            $answer = $model->itemsSold();
          } else {
            $answer = $model->itemsSoldRestore();
          }

          if (!$answer['status'])
            return '{"status":"danger","text":"' . $answer['text'] . '"}';
        }

        if (!$model->save()) {
          $message = $model->getErrors();
          $message = array_shift($message);

          return '{"status":"danger","text":"' . $message[0] . '"}';
        }

        // Подготовим вывод данных
        $data['status'] = "success";
        $data['html'] = $this->renderFile('@app/views/cart/_view.php', [
        'table_data' => [$model],
        ]);

        return json_encode($data);
      }

      return $this->renderFile('@app/views/cart/_form.php', [
      'form' => $model,
      ]);
    }

    /**
    *  Удалить фото
    */
    public function actionImageremove($id)
    {
      $model = $this->findModel($id);

      // Удалим фото
      $answer = $model->deleteImage();
      if (!$answer['status']) {
        return '{"status":"danger", "text":"'.$answer['text'].'", "code":"'.$answer['code'].'"}';
      }

      $model->image = "";
      if (!$model->save()) {
        $message = $model->getErrors();
        $message = array_shift($message);
        return '{"status":"danger","text":"' . $message[0] . '"}';
      }

      // Подготовим вывод данных
      $data['status'] = "success";
      $data['html'] = $this->renderFile('@app/views/cart/_view.php', [
      'table_data' => [$model],
      ]);

      return json_encode($data);
    }

    /**
    *  Удалить запись
    */
    public function actionDelete($id)
    {
      // Получим запись
      $model = $this->findModel($id);

      // Удалим все товары корзины
      Yii::$app->db->createCommand()->delete('cart_item', 'id_cart = '.$model->id_cart)->execute();

      // Удалим запись
      $this->findModel($id)->delete();
      return '{"status":"success", "text":"Запись удалена!"}';
    }

    /**
     *
     */
    protected function findModel($id)
    {
        if (($model = Cart::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Cart;
use app\models\CartItem;
use app\models\Site;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use yii\web\Cookie;

/**
 * CartController implements the CRUD actions for Cart model.
 */
class CartController extends Controller
{
  // Массив с меню содержит в себе два массива, массив с категориями (category)
  // и комнатами (subcategroy)
  public $page;
  // Мета тег description
  public $description;
  // Шаблон
  public $layout = 'wrapper';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'add' => ['POST'],
                    'delete' => ['POST'],
                    'update' => ['POST'],
                    'done' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Открывает корзину пользователя (COOKIE)
     */
    public function actionIndex()
    {
      $this->layout = "wrapper-top";
      $this->page = @\app\models\Site::page();
      $order = [];

      $cartHash = (array) json_decode(Site::getCookies("cartHash"));
      if ($cartHash) {
        $order = (new \yii\db\Query())
          ->from("cart")
          ->where(["hash" => $cartHash])
          ->all();
      }

      return $this->render('index', [
          'order' => $order,
      ]);
    }

    /**
     * Открывает заказ пользователя (БД)
     */
    public function actionOrder($id)
    {
      $this->layout = "wrapper-top";
      $this->page = @\app\models\Site::page();

      $order = (new \yii\db\Query())
        ->from("cart")
        ->where(["hash" => $id])
        ->one();

      $order_item = (new \yii\db\Query())
        ->from("cart_item")
        ->where(["id_cart" => $order["id_cart"]])
        ->all();

      return $this->render('order', [
          'order' => $order,
          'order_item' => $order_item,
      ]);
    }


    /**
     * Открывает корзину пользователя (COOKIE)
     */
    public function actionCheckout()
    {
      $this->layout = "wrapper-top";
      $this->page = @\app\models\Site::page();

      // получим данные корзины
      $cart = (array) json_decode(Site::getCookies("cart"));

      // Если есть корзина
      if (!$cart){
        return Yii::$app->response->redirect(['cart/index']);
      }

      // Сравним цены в корзине и в БД
      $cartItem = Cart::checkPriceCartCookie($cart);

      // Если цены изменились, обновим данные в COOKIE
      if ($cartItem["recount"]) {
        // Пересчитаем данные корзины
        $cart = Cart::recountCartCookie($cartItem["cartItem"]);

        // Запишем новые значения корзины и новый массив с товаром
        Site::setCookies("cart", json_encode($cart));
        Site::setCookies("cartItem", json_encode($cartItem["cartItem"]));
      }

      return $this->render('checkout', [
          'cart' => $cart,
          'cart_item' => $cartItem["cartItem"],
          'check_instock' => $cartItem["check_instock"],
      ]);
    }

    /**
     * Завершение оформления заказа, сохранение корзины в БД
     */
    public function actionDone()
    {
      $this->layout = "wrapper-top";
      $this->page = @\app\models\Site::page();

      // Сравним цены в корзине и в БД
      $cartItem = Cart::checkPriceCartCookie();
      // Если какой то из товаров отстутствует в наличии
      if (!$cartItem['check_instock']) {
        return '{"status":"danger", "text":"Этот товар уже кпили или на складе нет такого колличества, пожалуйста обновите страницу"}';
      }

      $cart = (array) $cartItem["cart"];

      // Если цены изменились, обновим данные в COOKIE
      if ($cartItem["recount"]) {
        // Пересчитаем данные корзины
        $cart = Cart::recountCartCookie($cartItem["cartItem"]);

        // Запишем новые значения корзины и новый массив с товаром
        Site::setCookies("cart", json_encode($cart));
        Site::setCookies("cartItem", json_encode($cartItem["cartItem"]));

        return '{"status":"danger","text":"Ваша корзина изменилась или цена на товар не совпадала. Пожалуйста, обновите страницу и попробуйте снова"}';
      }

      // Заполним и сохраним нашу корзину
      $model = new Cart;
      $model->attributes = $_POST;
      $model->attributes = [
          "price" => $cart["price"],
          "sale" => $cart["sale"],
          "price_total" => $cart["total"],
          "user_phone" => Cart::phoneSet($_POST["user_phone"]),
      ];
      if (!$model->save()) {
        $message = $model->getErrors();
        $message = array_shift($message);
        return '{"status":"danger","text":"' . $message[0] . '"}';
      }

      foreach ($cartItem["cartItem"] as $row) {
        $row = (array) $row;
        $model_item = new CartItem;
        $model_item->attributes = $row;
        $model_item->id_cart = $model->id_cart;
        $model_item->price_sale = $row["sale"];

        if (!$model_item->save()) {
          $message = $model_item->getErrors();
          $message = array_shift($message);
          return '{"status":"danger","text":"' . $message[0] . '"}';
        }
      }

      $result = $model->sendMailOrder(["cart"=>$model->toArray(), "cartItem"=>$cartItem]);
      if (!$result['status'])
        Yii::debug('Ошибка отправки почты');

      // Удалим данные о корзине, вместе с данными о товаре
      Site::delCookies("cart");
      Site::delCookies("cartItem");

      // Создадим новую переменную дял ID оформленного заказа
      Cart::hashSave($model->hash);
      return '{"status":"success", "text":"Спасибо за Ваш заказ! Сейчас мы переадресуем Вас на страницу заказа", "id":"'.$model->hash.'"}';
    }

    /**
      * Удаление товара из пользовательской корзины (COOKIE)
      * @param id - ID товара или ключ, из COOKIE[cartItam] вида id_furintures.'_'.id_color (21_3)
      */
    public function actionDelete()
    {
      // Получим из Cookie все содержимое корзины
      $cartItem = (array) json_decode(Site::getCookies("cartItem"));

      // Удалим переменную если она есть
      if ( isset($cartItem[$_POST["id"]]) )
        unset($cartItem[$_POST["id"]]);

      // Пересчитаем данные корзины
      $cart = Cart::recountCartCookie($cartItem);

      // Запишем новые значения корзины и новый массив с товаром
      Site::setCookies("cart", json_encode($cart));
      Site::setCookies("cartItem", json_encode($cartItem));

      // Выведем код корзины для вставки
      $data['status'] = "success";
      $data['html'] = $this->renderFile('@app/views/cart/_index_cart.php', [
          'cart' => $cart,
          'cart_item' => $cartItem,
      ]);
      $data['html_menu'] = $this->renderFile('@app/views/cart/_cart.php', [
          'cart' => $cart,
          'cart_item' => $cartItem,
      ]);

      return json_encode($data);
    }


    // public function actionTest()
    // {
    //   $cart = (array) json_decode(Site::getCookies("cart"));
    //   $cartItem = (array) json_decode(Site::getCookies("cartItem"));
    //   $cartHash = (array) json_decode(Site::getCookies("cartHash"));
    //
    //   echo "<pre>";
    //   print_r($cart);
    //   print_r($cartItem);
    //   print_r($cartHash);
    //   echo "</pre>";
    //   return;
    // }

    /**
      * Удаление товара из пользовательской корзины (COOKIE)
      * @param id - ID товара или ключ, из COOKIE[cartItam] вида id_furintures.'_'.id_color (21_3)
      * @param count - Новое кол-во товара
      */
    public function actionUpdate()
    {
      // Получим из Cookie все содержимое корзины
      $cartItem = (array) json_decode(Site::getCookies("cartItem"));

      // Если такой товар есть, изменим его кол-во и цену
      if ( isset($cartItem[$_POST["id"]]) ){
        $cartItem[$_POST["id"]] = (array) $cartItem[$_POST["id"]];
        $price = $cartItem[$_POST["id"]]["price"] / $cartItem[$_POST["id"]]["count"];
        $sale = $cartItem[$_POST["id"]]["sale"] / $cartItem[$_POST["id"]]["count"];
        $cartItem[$_POST["id"]]["count"] = (int) $_POST["count"];
        $cartItem[$_POST["id"]]["price"] = $price * $cartItem[$_POST["id"]]["count"];
        $cartItem[$_POST["id"]]["sale"] = $sale * $cartItem[$_POST["id"]]["count"];
      }

      // Пересчитаем данные корзины
      $cart = Cart::recountCartCookie($cartItem);

      // Запишем новые значения корзины и новый массив с товаром
      Site::setCookies("cart", json_encode($cart));
      Site::setCookies("cartItem", json_encode($cartItem));

      // Выведем код корзины для вставки
      $data['status'] = "success";
      $data['html'] = $this->renderFile('@app/views/cart/_index_cart.php', [
          'cart' => $cart,
          'cart_item' => $cartItem,
      ]);
      $data['html_menu'] = $this->renderFile('@app/views/cart/_cart.php', [
          'cart' => $cart,
          'cart_item' => $cartItem,
      ]);

      return json_encode($data);
    }


    /**
      * Довавляет в Cookie корзину и данные по товару, который добавили в корзину
      * @param _POST[id_items] - id товара, который добавляем в корзину
      * @param _POST[color] - id цвета товара
      * @param _POST[count] - Кол-во товара
      */
    public function actionAdd()
    {
      // Создадим и запишем все данные о добавляемом товаре
      $cartItem = Cart::initCartItemCookie($_POST);
      if (!$cartItem["status"])
        return json_encode(["status"=>"danger", "text"=>$cartItem['text']]);
      $cartItem = $cartItem["data"];

      // Пересчитаем данные корзины
      $cart = Cart::recountCartCookie($cartItem);

      // Запишем новые значения корзины и новый массив с товаром
      Site::setCookies("cart", json_encode($cart));
      Site::setCookies("cartItem", json_encode($cartItem));

      // Выведем код корзины для вставки
      $data['status'] = "success";
      $data['html'] = $this->renderFile('@app/views/cart/_cart.php', [
          'cart' => $cart,

frontend/views/cart/_cart.php
<?php
use yii\helpers\Url;
?>

<?php if (count($cart_item)): ?>
  <ul>
    <?php
    echo Yii::$app->view->renderFile('@app/views/cart/_cart_item.php', [
      "cart_item" => $cart_item,
    ]);
    ?>
    <li>
      <div class="subtotal">
        <div class="subtotal-titles">
          <h3>Цена без скидки :</h3>
          <span><?= $cart["price"] ?></span>
        </div>
        <div class="subtotal-titles">
          <h3>Скидка :</h3>
          <span><?= $cart["sale"] ?></span>
        </div>
        <div class="subtotal-titles">
          <h3>Итого :</h3>
          <span><?= $cart["total"] ?></span>
        </div>
      </div>
    </li>
    <li>
      <div class="cart-btns">
        <span class="default-btn">
          <a href="<?= Url::to(['cart/index']) ?>">Открыть</a>
        </span>
        <span class="default-btn">
          <a href="<?= Url::to(['cart/checkout']) ?>">Оформить</a>
        </span>
      </div>
    </li>
  </ul>
<?php endif; ?>

frontend/views/cart/_cart_item.php
<?php
use yii\helpers\Url;
?>

<?php if (count($cart_item)): ?>
  <?php foreach ($cart_item as $row):
    $row = (array) $row; ?>
    <li id="cart-item">
      <div class="cart-img">
        <a href="<?= Url::to(['items/view', 'id'=>$row["id_items"]]) ?>"><img src="/img/items/<?= $row["image"] ?>" alt="" /></a>
      </div>
      <div class="cart-title">
        <a href="<?= Url::to(['items/view', 'id'=>$row["id_items"]]) ?>"><h4><?= $row["title"] ?></h4></a>
        <span class="quantity"> × <?= $row["count"] ?></span>
        <span class="cart-price"><?= $row["price"] ?> р.</span>
      </div>
    </li>
  <?php endforeach; ?>
<?php endif; ?>

frontend/views/cart/_index_cart.php
<?php
use yii\helpers\Url;
?>

<?php if (isset($cart) && count($cart) && count($cart_item)): ?>
<div class="table-content table-responsive">
  <table>
    <thead>
      <tr>
        <th class="product-thumbnail">Фото</th>
        <th class="product-name">Наименование</th>
        <th class="product-price">Цена</th>
        <th class="product-quantity">Количество</th>
        <th class="product-subtotal">Стоимость</th>
        <th class="product-remove">Удалить</th>
      </tr>
    </thead>
    <tbody>

      <?php
        echo Yii::$app->view->renderFile('@app/views/cart/_index_cart_item.php', [
          "cart_item" => $cart_item,
        ]);
      ?>

    </tbody>
  </table>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="cart_totals">
      <h3>К оплате</h3>
      <br />
      <table>
        <tbody>
          <tr class="cart-subtotal">
            <th>Цена без скидки:</th>
            <td><span class="amount"><?= $cart["price"] ?></span></td>
          </tr>
          <tr class="cart-subtotal">
            <th>Скидка:</th>
            <td><span class="amount"><?= $cart["sale"] ?></span></td>
          </tr>
          <tr class="order-total">
            <th>Итого:</th>
            <td>
              <strong><span class="amount"><?= $cart["total"] ?></span></strong>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="wc-proceed-to-checkout">
        <a href="<?= Url::to(['cart/checkout']) ?>">Оформить заказ</a>
      </div>
    </div>
  </div>
</div>
<?php else: ?>
  <p class="empty-alert mt4">В корзине пока пусто :-(</p>
<?php endif; ?>

frontend/views/cart/_index_cart_item.php
<?php
use yii\helpers\Url;
?>

<?php if (count($cart_item)): ?>
  <?php foreach ($cart_item as $key => $row):
    $row = (array) $row;
    $price = $row["price"] - $row["sale"]; ?>

    <tr id="<?= $key ?>">
      <td class="product-thumbnail">
        <a href="/img/items/<?= str_replace("/@", "/", $row["image"]) ?>" class="popup-link">
          <img src="/img/items/<?= $row["image"] ?>" alt="" />
        </a>
      </td>

      <td class="product-name"><a href="<?= Url::to(['items/view', 'id'=>$row["id_items"]]) ?>"><?= $row["title"] ?></a></td>
      <td class="product-price"><span class="amount"><?= ( $price/$row["count"] ) ?> р.</span></td>
      <td class="product-quantity">
        <input type="number" name="cart-item-count" value="<?= $row["count"] ?>" min="1" max="100" />
      </td>
      <td class="product-subtotal"><?= $price ?> р.</td>

      <td class="product-remove">
        <a href="javascript:void(0);" id="cart-item-delete">
          <i class="fa fa-times"></i>
        </a>
      </td>
    </tr>

  <?php endforeach; ?>
<?php endif; ?>

frontend/views/cart/checkout.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Оформление заказа - Экспресс Мебель';
$this->context->description = 'Оформление заказа';
$h1 = 'Оформление заказа';

$seoPage = @app\models\Site::getSeoPage();
if (!empty($seoPage)) {
  $this->title = $seoPage['title'];
  if (strlen($seoPage['description']))
    $this->context->description = $seoPage['description'];
  if (strlen($seoPage['h1']))
    $h1 = $seoPage['h1'];
}
?>

<script src="/js/page/checkout.js"></script>

<div class="breadcrumb-banner-area ptb-100">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb-text text-center">
          <div class="breadcrumb-menu">
            <h1 class="page-title"><?=  $h1 ?></h1>
            <ul>
              <li><a href="<?= Url::to(['/']) ?>">Главная</a></li>
              <li><a href="<?= Url::to(['cart/index']) ?>">Корзина</a></li>
              <li><span>Оформление</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="checkout-area pt-30 pb-30">
  <div class="container">
    <div class="row">
      <form id="form-checkout">
        <div class="col-lg-6 col-md-6">
          <div class="checkbox-form">
            <h3>Детали заказа</h3>
            <div class="row">
              <div class="col-md-12">
                <div class="checkout-form-list">
                  <label>Имя <span class="required">*</span></label>
                  <input type="text" id="user_name" name="user_name" />
                </div>
              </div>
              <div class="col-md-12">
                <div class="checkout-form-list">
                  <label>Телефон <span class="required">*</span></label>
                  <input type="text" id="user_phone" name="user_phone" placeholder="7 900 123 456 78" />
                </div>
              </div>
              <div class="col-md-12">
                <div class="checkout-form-list create-acc">
                  <input type="checkbox" id="delivery" name="delivery" />
                  <label for="delivery">Нужна доставка?</label>
                </div>
                <div id="delivery_address" class="checkout-form-list">
                  <p>Напишите, пожалуйста, полный адрес доставки, чтобы наша доставка согла Вас найти.</p>
                  <label>Адрес  <span class="required">*</span></label>
                  <input type="text" id="user_address" name="user_address" placeholder="ул. Красная д. 123 п. 2" />
                </div>
              </div>
              <div class="col-md-12">
                <div class="checkout-form-list">
                  <label>Комментарий к заказу</label>
                  <textarea id="comment" name="comment" rows="10" placeholder="Текст комментария" ></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="your-order">
            <h3>Ваш заказ</h3>
            <div class="your-order-table table-responsive">
              <table>
                <thead>
                  <tr>
                    <th class="product-name">Наименование</th>
                    <th class="product-total">Стоимость</th>
                  </tr>
                </thead>
                <tbody>

                  <?php if (isset($cart_item) && count($cart_item))
                    foreach ($cart_item as $key => $row):
                    $row = (array) $row; ?>
                    <tr class="cart_item">
                      <td class="product-name">
                        <?= $row["title"] ?>
                        <?php if ($row["color"]): ?>
                          (Цвет: <?= $row["color"] ?>)
                        <?php endif; ?>
                        <strong class="product-quantity"> × <?= $row["count"] ?> </strong>
                        <?php if (!$row['check_instock']): ?>
                          <span class="text-danger">Товара нет в наличии</span>
                        <?php endif; ?>
                      </td>
                      <td class="product-total">
                        <span class="amount"><?= $row["sale"] ? ($row["price"] - $row["sale"]) : $row["price"] ?> р.</span>
                      </td>
                    </tr>
                  <?php endforeach; ?>

                </tbody>
                <tfoot>
                  <tr class="cart-subtotal">
                    <th>Цена без скидки:</th>
                    <td><span class="amount"><?= $cart["price"] ?> р.</span></td>
                  </tr>
                  <tr class="cart-subtotal">
                    <th>Скидка:</th>
                    <td><span class="amount"><?= $cart["sale"] ?> р.</span></td>
                  </tr>
                  <tr class="order-total">
                    <th>Итого:</th>
                    <td><strong><span class="amount"><?= $cart["total"] ?> р.</span></strong>
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
            <div class="payment-method">
              <div class="order-button-payment">
                <button type="submit"<?= !$check_instock ? "disabled" : "" ?>>Разместить заказ</button>
                <?php if (!$check_instock): ?>
                  <p class="text-danger text-center mt2">В вашей корзине есть товар, которого нет в наличии. Пожалуйста выберите другой товар или удалите его из корзины.</p>
                <?php endif; ?>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

frontend/views/cart/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Ваша корзина - Экспресс Мебель';
$this->context->description = 'Ваша корзина';
$h1 = 'Корзина';

$seoPage = @app\models\Site::getSeoPage();
if (!empty($seoPage)) {
  $this->title = $seoPage['title'];
  if (strlen($seoPage['description']))
    $this->context->description = $seoPage['description'];
  if (strlen($seoPage['h1']))
    $h1 = $seoPage['h1'];
}

if (!isset($cart) && app\models\Site::hasCookies("cart")) {
  $cart = (array) json_decode(app\models\Site::getCookies("cart"));
  $cart_item = (array) json_decode(app\models\Site::getCookies("cartItem"));
} else {
  $cart = [];
  $cart_item = [];
}
?>

<script src="/js/page/cart.js"></script>

<div class="breadcrumb-banner-area ptb-100">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb-text text-center">
          <div class="breadcrumb-menu">
            <h1 class="page-title"><?=  $h1 ?></h1>
            <ul>
              <li><a href="<?= Url::to(['/']) ?>">Главная</a></li>
              <li><span>Корзина</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="cart-main-area pb-50">
  <div class="container">
    <div class="col-md-12">
      <?php if (isset($order)): ?>
      <div class="isotope-filter faq-filter text-center mt6">
        <button data-filter="#cart">Корзина <?= count($cart_item) ? "(".count($cart_item).")" : "" ?></button>
        <button data-filter="#order">Мои заказы <?= count($order) ? "(".count($order).")" : "" ?></button>
      </div>
      <?php endif; ?>
    </div>

    <div class="col-md-12">
      <div class="isotope-grid">

        <div class="isotope-item faq-isotope-item" id="cart">
          <?php
          echo Yii::$app->view->renderFile('@app/views/cart/_index_cart.php', [
            "cart" => $cart,
            "cart_item" => $cart_item,
          ]);
          ?>
        </div>

        <?php if (isset($order)): ?>
        <div class="isotope-item faq-isotope-item" id="order">
          <div class="section-title text-center">
            <div class="list-group">
              <?php foreach ($order as $key => $row): ?>
                <a href="<?= Url::to(["cart/order", "id" => $row["hash"]]) ?>" class="list-group-item">
                  Заказ №<?= $key + 1 ?> от <i><?= date("d.m.Y", strtotime($row["created_at"])) ?></i> на сумму <b><?= $row["price_total"] ?></b>
                </a>
              <?php endforeach ?>
            </div>
          </div>
        </div>
        <?php endif; ?>

      </div>
    </div>
  </div>
</div>